# Generated by Django 5.2.6 on 2025-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_in',
            field=models.IntegerField(default=300),
        ),
    ]
