# Generated by Django 5.2.6 on 2025-09-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_alter_otp_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
