# Generated by Django 5.2.6 on 2025-09-14 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_projects_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='#1E1E1E', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Color must be a valid HEX code like #RRGGBB or #RGB.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
