# Generated by Django 5.2.6 on 2025-09-14 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_comment_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('off_track', 'Off Track'), ('on_hold', 'On Hold'), ('complete', 'Complete')], default='on_track', max_length=20, validators=[django.core.validators.RegexValidator(message='Status must be a valid choice.', regex='^(on_track|at_risk|off_track|on_hold|complete)$')]),
        ),
    ]
