# Generated by Django 5.2.6 on 2025-09-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('project', 'order')},
        ),
    ]
