# Generated by Django 5.2.6 on 2025-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=10),
        ),
    ]
