# Generated by Django 5.2.6 on 2025-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('', ''), ('List', 'List'), ('BarChart', 'BarChart'), ('Layers', 'Layers'), ('Calendar', 'Calendar'), ('Rocket', 'Rocket'), ('Users', 'Users'), ('TrendingUp', 'TrendingUp'), ('Star', 'Star'), ('Bug', 'Bug'), ('Lightbulb', 'Lightbulb'), ('Globe', 'Globe'), ('Settings', 'Settings'), ('FileText', 'FileText'), ('Monitor', 'Monitor'), ('CheckCircle', 'CheckCircle'), ('Target', 'Target'), ('Code', 'Code'), ('Megaphone', 'Megaphone'), ('MessageCircle', 'MessageCircle'), ('Briefcase', 'Briefcase')], default='Globe', max_length=30, null=True),
        ),
    ]
