# Generated by Django 5.2.6 on 2025-09-27 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#5EC5DC', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid HEX code like #RRGGBB or #RGB.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
