# Generated by Django 5.2.6 on 2025-09-29 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_project_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('section', 'order'), name='unique_task_order_per_section'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('project', 'order'), name='unique_task_order_per_project'),
        ),
    ]
